### ISSUE TITLE
How to use the tokenizer

### ISSUE THREAD

**Issue by justeuer** [MeLeLBGU/SaGe#2]
Hi,

I‘ve trained a tokenizer and obtained the following result folder:

bpe_vanilla_encoding.txt  
bpe_vanilla_vocab.txt  
sg_bpe_encoding.txt  
sg_bpe_vocab.txt
bpe_vanilla.model         
current_vocab.bin      
sg_bpe.model         
sg_log_probs_without_tokens_mp.txt
bpe_vanilla_only.txt      
embeddings.bin         
sg_bpe_only.txt      
sorted_tokens_sg.bin
bpe_vanilla.vocab         
seed.txt               
sg_bpe.vocab         
token_to_line_indices_dict.bin

How should I proceed to use the tokenizer? Did you use the BertTokenizer class from Huggingface and simply load the `sg_bpe_vocab.txt` file?

**Comment by yuvalpinter** [comment]
Yes, either that or the `sg_bpe.vocab` file (@shakedyeh why are there two?). Specifically we used the `academic-budget-bert` package for our model training but that inherits from huggingface so it should be fine.

Let us know if you have any feedback, or more issues!
- Yuval
