### ISSUE TITLE
SaGe V2

### ISSUE THREAD

**Issue by yuvalpinter** [MeLeLBGU/SaGe#3]
Integrate the `faster sage` algorithm into the repository, parallelizing the search for `(ablation candidate, target, context)` triplets over the corpus thus making the ablation phase roughly x200 faster than in V1.

**Comment by tenebrius** [comment]
Hi great work on this. I want to use this but it is really slow. Can please integrate the new version. 
Thanks a lot

**Comment by yuvalpinter** [comment]
Thanks for reaching out. Our current estimate is on or before January 4.

**Comment by tenebrius** [comment]
Great. Thank you

**Comment by yuvalpinter** [comment]
@tenebrius only a week late, please try it out :)

**Comment by tenebrius** [comment]
@yuvalpinter Thanks I'll report the results
